### PR TITLE
Fix filter to also take added entities into account

### LINKED ISSUE #27: Write history when adding a new item to the database
Why is the `EntityState.Added` not supported? The case for the `EntityState.Added` is [here](https://github.com/Arch/AutoHistory/blob/3bcda4cfd3f8fb89cb43df958ce64aa59b3c4c4a/src/Microsoft.EntityFrameworkCore.AutoHistory/Extensions/DbContextExtensions.cs#L55).

But the filter on [Line 33](https://github.com/Arch/AutoHistory/blob/3bcda4cfd3f8fb89cb43df958ce64aa59b3c4c4a/src/Microsoft.EntityFrameworkCore.AutoHistory/Extensions/DbContextExtensions.cs#L33) filters for `modified` and `deleted`

### PR DESCRIPTION
**Pull request by Franklin89**
fixes #27

### CODE REVIEW

**Comment by xyting** [comment]
This codes not work because the Added entity’s primary key value is wrong in it’s history without one more database roundtrip

**Comment by Franklin89** [comment]
You got a valid point there!

Hmm i guess there is no solution other than hitting the database twice. In my case I use a GUID as an Id and create that in code on SaveChanges so this would not be an issue. 

Idea: make the events configureable and leave added out of the standard configuration and let people decide if they want it.

**Comment by xyting** [comment]
Yeah, if the primary key isn't database generated, such as in your case, use code generated GUID,  will not be an issue.

Your idea could be impl in this PR?

**Comment by Franklin89** [comment]
You mean the configuration? Sure, ill make an update asap! Maybe i can do it this afternoon (european time) 👍🏼

**Comment by xyting** [comment]
@Franklin89 Have you made any progress?

**Comment by xyting** [comment]
Close because no more info

**Pull request closed without merging**
