### PR TITLE
Master

### PR DESCRIPTION
**Pull request by SergeyIlyin**

### CODE REVIEW

**Comment by SergeyIlyin** [comment]
Update to use 4.5.1 for next same Update of UnitOfWork

**Comment by xyting** [comment]
@SergeyIlyin Thanks, LGTM.

**Comment by xyting** [comment]
@SergeyIlyin I need to pack a new package for the UnitOfWork?

**Comment by xyting** [comment]
@SergeyIlyin <TargetFrameworks>net4.5.1;netstandard1.6.1</TargetFrameworks> SHOULD <TargetFrameworks>net451;netstandard1.6.1</TargetFrameworks>, [see more](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/libraries.md#how-to-multitarget)

**Comment by SergeyIlyin** [comment]
It my fail. I will correct it in  hour.

**Comment by xyting** [comment]
I had fixed it, and release new version to include your PR, see [v1.1.2](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.AutoHistory?NormalizedVersion=1.1.2)

**Comment by SergeyIlyin** [comment]
Oh. It corrected. Thanks.

**Pull request merged**
